### PR TITLE
Adding VehicleOdometry.

### PR DESCRIPTION
**Pull request by pijaro**
Vehicle odometry message for tracking vehicle velocity and wheel angles. Used for `VehicleOdometryData` type with LGSVL `VehicleOdometrySensor` sensor.

### CODE REVIEW

**Comment by ruffsl** [comment]
@hadiTab is this still needed for migration in Autoware.auto?
* https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/issues/580

**Comment by hadiTab** [comment]
@ruffsl based on [this discussion](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/issues/365#note_429561272) it seems like it is needed, though I'm not 100% sure I understand why.
I will merge this shortly, but we will need to make some changes in the simulator side for it to be published by our bridge (ros2-lgsvl-bridge). I'm guessing it will work with the native bridge though.

**Comment by ruffsl** [comment]
> though I'm not 100% sure I understand why

There is a difference between the ground truth state vs the ego-estimate of the vehicle. Having a means of synthesizing sensor feedback or observing dynamics with noise is useful for realistic simulations.

https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/issues/365#note_433922742

**Comment by hadiTab** [comment]
I guess my point was that the data present in this message can be calculated from other messages (such as GPS and CanBus). But you are right this does at the possibility of adding sensor noise to make it more realistic (though this isn't in place right now).

The commit has been brought in with the latest update.

**Comment by ruffsl** [comment]
> the data present in this message can be calculated from other messages (such as GPS and CanBus)

CanBus doesn't report wheel angle/radius or rotational velocity, so wouldn't help with ego-odometry here.

https://github.com/lgsvl/lgsvl_msgs/blob/0e5e7bd3660dcd25fefef44bef093cd034875769/msg/CanBusData.msg#L1

**Comment by ruffsl** [comment]
@hadiTab , you may want to check if the types all match, given `autoware_auto_msgs/msg/VehicleOdometry.idl` uses a time stamp:

https://gitlab.com/autowarefoundation/autoware.auto/autoware_auto_msgs/-/blob/master/autoware_auto_msgs/msg/VehicleOdometry.idl#L8

And `lgsvl_msgs/msg/VehicleOdometry.msg` just included is using a header type:

https://github.com/lgsvl/lgsvl_msgs/blob/0e5e7bd3660dcd25fefef44bef093cd034875769/msg/VehicleOdometry.msg#L1

And `master` branch for `simulator/Assets/Scripts/Bridge/Ros/RosConversions.cs` uses a stamp

https://github.com/lgsvl/simulator/blob/8b02c852c0642347f0b05125c726ceb09bfa0b26/Assets/Scripts/Bridge/Ros/RosConversions.cs#L494

but the `VehicleOdometry` is missing from `simulator/Assets/Scripts/Bridge/Ros2/Messages/Lgsvl.cs` in the more recent `release-2020.06` branch

https://github.com/lgsvl/simulator/blob/dc173a2df5cdff155455074d49529cccb58ef3f3/Assets/Scripts/Bridge/Ros2/Messages/Lgsvl.cs

**Comment by hadiTab** [comment]
> > the data present in this message can be calculated from other messages (such as GPS and CanBus)
> 
> CanBus doesn't report wheel angle/radius or rotational velocity, so wouldn't help with ego-odometry here.
> 
> https://github.com/lgsvl/lgsvl_msgs/blob/0e5e7bd3660dcd25fefef44bef093cd034875769/msg/CanBusData.msg#L1

Ah, I didn't realize the steering feedback in CanBus is percentage. I guess it isn't obvious (or convenient) how to convert that to wheel angle.



> @hadiTab , you may want to check if the types all match, given `autoware_auto_msgs/msg/VehicleOdometry.idl` uses a time stamp:
> 
> https://gitlab.com/autowarefoundation/autoware.auto/autoware_auto_msgs/-/blob/master/autoware_auto_msgs/msg/VehicleOdometry.idl#L8
> 
> And `lgsvl_msgs/msg/VehicleOdometry.msg` just included is using a header type:
> 
> https://github.com/lgsvl/lgsvl_msgs/blob/0e5e7bd3660dcd25fefef44bef093cd034875769/msg/VehicleOdometry.msg#L1
> 
> And `master` branch for `simulator/Assets/Scripts/Bridge/Ros/RosConversions.cs` uses a stamp
> 
> https://github.com/lgsvl/simulator/blob/8b02c852c0642347f0b05125c726ceb09bfa0b26/Assets/Scripts/Bridge/Ros/RosConversions.cs#L494
> 
> but the `VehicleOdometry` is missing from `simulator/Assets/Scripts/Bridge/Ros2/Messages/Lgsvl.cs` in the more recent `release-2020.06` branch
> 
> https://github.com/lgsvl/simulator/blob/dc173a2df5cdff155455074d49529cccb58ef3f3/Assets/Scripts/Bridge/Ros2/Messages/Lgsvl.cs

I'm a bit confused about what the issue with the stamp is that you're referring to. Both seem to be outputting ros-type stamps for the header (sec/nsec).

As for the `VehicleOdometry` missing from the `release-2020.06` branch, that is right. This is the "change" I was referring to in my first comment that we will need to make on the simulator side.

**Comment by ruffsl** [comment]
> I'm a bit confused about what the issue with the stamp is that you're referring to. Both seem to be outputting ros-type stamps for the header (sec/nsec).

The `Time` type does not equate to the `Header` type.
A `Header` struct does contain a `stamp` field of type `Time`, as well as a `frame_id` of type `string`.

https://github.com/ros2/common_interfaces/blob/975f1ce52645a9eabe27a222ceb43bbbba268956/std_msgs/msg/Header.msg#L5-L9

The autoware.auto `VehicleOdometry.idl` declares a `stamp` field of type `Time`; no `Header`. This is consistent in the previous bridge code, missing from the new bridge code, and inconsistent with the recently added `VehicleOdometry.msg` in `lgsvl_msg`.

**Comment by hadiTab** [comment]
Got it. You are right, I missed that. I'll commit a fix for it. Thanks for pointing it out.

**Comment by hadiTab** [comment]
@ruffsl Actually I changed my mind. I'm going to leave it as a header. Changing it to stamp makes the code more complicated as ROS and ROS2 have different message types for Time. We don't have a requirement for having our types match `autoware_auto_msgs` and the purpose of the `lgsvl_interface` in Autoware Auto is to handle such conversions.

If there is some other reason to not include a header, please let me know. Thanks.

**Comment by ruffsl** [comment]
> If there is some other reason to not include a header, please let me know. Thanks.

That's fine. I'm not sure why `autoware_auto_msgs` went with only a stamp as opposed to a full header, perhaps to save bytes over the wire for a high frequency topic like odometry. Just wanted to verify if the departure was intentional.

**Pull request closed without merging**
